<?php
$taxvat = false;

if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $attribute_config = Mage::getStoreConfig('payment/pagcommerce_payment/customer_taxvat_attribute');
    $taxvat = $customer->getData($attribute_config);
}
$_code = $this->getMethodCode();
/** @var Pagcommerce_Payment_Model_Method_Pix $method */
$method = $this->getMethod();
$instructions = $method->getConfigData('instructions');
?>


<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if($instructions): ?>
        <li>
            <?php echo nl2br($instructions) ?>
        </li>
    <?php endif; ?>
    <li>
        <label for="cpfcnpjboleto"> Informe seu CPF/CNPJ: </label>
        <input type="text" id="cpfcnpjboleto" name="cpfcnpjboleto" value="<?php echo $taxvat; ?>" class="pagcommerce_documento required-entry input-text" maxlength="18">
    </li>
</ul>



<script type="text/javascript">
    jQuery(document).on('click', 'input[name="payment[method]"]', function(){
        applyPagcommerceValidations('boleto');
    });
    applyPagcommerceValidations('boleto');
</script>