<?php
$hasVat = false;
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $attribute_config = Mage::getStoreConfig('payment/pagcommerce_payment/customer_taxvat_attribute');
    $hasVat = $customer->getData($attribute_config);
}
$_code = $this->getMethodCode();

/** @var Pagcommerce_Payment_Model_Method_Pix $method */
$method = $this->getMethod();
$instructions = $method->getConfigData('instructions');
?>

<?php if($instructions): ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
        <li>
           <?php echo nl2br($instructions) ?>
        </li>

    </ul>
<?php endif; ?>


<?php if(!$hasVat):?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>">
        <li>
            <label for="cpfcnpjpix">Informe seu CPF/CNPJ: </label>
            <input type="text" id="cpfcnpjpix" name="cpfcnpjpix" class="pagcommerce_documento required-entry input-text" maxlength="18">
        </li>
    </ul>
<?php else: ?>
    <input type="hidden" class="pg_has_document" value="1"/>
<?php endif; ?>

