<?php
    /** @var Pagcommerce_Payment_Block_Info_Pix $this */
    /** @var Mage_Sales_Model_Order $order */
    $order = $this->getInfo()->getOrder();
    echo "Forma de Pagamento: ".Mage::getStoreConfig('payment/pagcommerce_payment_cc/title').'<br>';
    $payment = $order->getPayment();

    $additional = $payment->getAdditionalInformation();
    echo '<br>';
    echo $additional['payment_description'];
    echo '<br>';
    echo '<br>';
    ?>
