<script>

    function applyPagcommerceValidations(method){
        inputMethood = jQuery('input[name="payment[method]"]:checked');
        if(jQuery(inputMethood).length){
            elementId = jQuery(inputMethood).attr('id');
            elementTargetName = 'p_method_pagcommerce_payment_'+method;

            elementDocument =  jQuery('#cpfcnpj'+method);
            if(elementId == elementTargetName){
                  console.log('Obriga '+method);
                  jQuery(elementDocument).addClass('required-entry');
                  jQuery(elementDocument).removeClass('validation-passed');
            }else{
                console.log('Não Obriga '+method);
                jQuery(elementDocument).removeClass('required-entry');
                jQuery(elementDocument).addClass('validation-passed');
            }
            return true;
        }
    }

     jQuery(document).on('keyup', '.pagcommerce_documento', function(){
        var cpfcnpj = $j(this).val();
        elementId = jQuery(this).attr('id');
        if (cpfcnpj.length >= 14){
            VMasker(document.getElementById(elementId)).maskPattern('99.999.999/9999-99');
        }
        else{
            VMasker(document.getElementById(elementId)).maskPattern('999.999.999-99');
        }

    });


</script>
