<?php
/** @var Pagcommerce_Payment_Block_Checkout_Success $this */
$order = $this->getOrder();

/** @var Pagcommerce_Payment_Helper_Data $helper */
$helper = Mage::helper('pagcommerce_payment');

if($order && $order->getId()):
?>

<div class="cctheme-onepagesuccess">
   <?php
    $payment = $order->getPayment();
    $data = $payment->getMethodInstance()->getInfoInstance()->getAdditionalInformation();

    if ($data && $order->getPayment()->getMethod() == 'pagcommerce_payment_boleto'):
        if (isset($data['boleto']) && $data['boleto']):
            ?>
            <div class="cctheme-payment-block" id="boleto">
                <div class="cctheme-payment-block-title">
                    <img src="<?php echo $this->getSkinUrl('pagcommerce_payment/img/boleto-icon.png"') ?>" alt="Boleto Bancário" class="cctheme-image" width="28" height="32">
                    <span class="cctheme-text">Realize o pagamento do boleto bancário para finalizar a sua compra</span>
                </div>
                <div class="content">
                    <div class="cctheme-payment-summary">
                        <!-- <small class="cctheme-small summary-text">Utilize este código de barras e pague o boleto pelo celular</small> -->
                        <!-- <div class="img-wrapper">
                            <div class="img">
                                <?php
                                    /** @var Pagcommerce_Payment_Helper_Barcode $barcodeHelper */
                                    $barcodeHelper = Mage::helper('pagcommerce_payment/barcode');
                                ?>
                                <?php echo $barcodeHelper->getImgBarCode($data['boleto']['boleto_barcode']); ?>
                            </div>
                        </div> -->

                        <div class="input-barcode">
                            <input class="input" type="text" readonly="" value="<?php echo $data['boleto']['boleto_digitable_line'] ?>">
                        </div>

                        <div class="actions-toolbar">
                            <a href="<?php echo $data['boleto']['boleto_url']; ?>" target="_blank" title="Imprimir boleto" aria-label="Imprimir boleto" class="action primary">
                                <span class="cctheme-text">Imprimir boleto</span>
                            </a>
                            <button type="button" title="Copiar código de barras" aria-label="Copiar código de barras" class="action copy secondary boleto" data-clipboard-text="<?php echo $data['boleto']['boleto_digitable_line'] ?>">
                                <span class="cctheme-icon">
                                    <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M12.182 12.1818H16.0002V2H5.81836V5.81818" stroke="#4a4948" stroke-width="1.27273" stroke-linecap="round" stroke-linejoin="round"></path>
                                        <path d="M12.1818 5.81824H2V16.0001H12.1818V5.81824Z" stroke="#4a4948" stroke-width="1.27273" stroke-linecap="round" stroke-linejoin="round"></path>
                                    </svg>
                                </span>
                                <span class="cctheme-text">Copiar código</span>
                            </button>
                        </div>
                    </div>
                    <div class="cctheme-payment-content">
                        <div class="title">
                            <div class="label">
                                <span class="cctheme-text">Valor da sua compra:</span>
                            </div>
                            <div class="grand-total">
                                <span class="price"><?php echo Mage::helper('core')->currency($order->getGrandTotal(), true, false); ?></span>
                            </div>
                        </div>
                        <div class="cctheme-payment-steps">
                            <div class="step">
                                <p class="text-danger">Atenção, o boleto pode levar até 5 minutos para ser registrado</p>
                            </div>
                            <div class="step">
                                <p class="cctheme-text"><strong class="cctheme-strong">1. </strong>Copie o código do boleto acima.</p>
                            </div>
                            <div class="step">
                                <p class="cctheme-text"><strong class="cctheme-strong">2. </strong>Acesse o site ou o app do seu banco para seguir com o pagamento.</p>
                            </div>
                            <div class="step">
                                <p class="cctheme-text"><strong class="cctheme-strong">3. </strong>Você tem até <?php echo $helper->getConfig('boleto', 'days'); ?> dias para pagar esse boleto.</p>
                            </div>
                            <div class="step">
                                <p class="cctheme-text"><strong class="cctheme-strong">Atenção: </strong>o banco tem o prazo de até três dias úteis para confirmar o pagamento do boleto.
                                    O prazo de entrega do produto começa a ser contado a partir dessa confirmação.</p>
                            </div>
                        </div>

                        <div class="cctheme-payment-brand">
                            <div>
                                <small class="cctheme-small">pagamento processado por:</small>
                            </div>
                            <div>
                                <a href="https://pagcommerce.com.br" target="_blank" title="Ir para o site da Pagcommerce" aria-label="Ir para o site da Pagcommerce">
                                    <img class="cctheme-image"  src="<?php echo $this->getSkinUrl('pagcommerce_payment/img/pagcommerce-pagamentos-online.webp') ?>"  alt="Pagcommerce - Pix para Ecommerce" width="96" height="21"/>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <style>
                <?php echo $barcodeHelper->getCss(); ?>
            </style>
        <?php endif; ?>
    <?php endif; ?>



    <?php if ($data && $order->getPayment()->getMethod() == 'pagcommerce_payment_pix'):

        $showQrCodeMobile = false;
        $qrCodeClass = $showQrCodeMobile ? '' : 'pag-hide-mobile';

        if (isset($data['pix']['pix_qrcode']) && $data['pix']['pix_string']):
            ?>
            <div class="cctheme-payment-block pix-pendente" id="pix">
                    <div class="cctheme-payment-block-title">
                        <img src="<?php echo $this->getSkinUrl('pagcommerce_payment/img/pix-icon.svg"') ?>" alt="Logo Pix" class="cctheme-image" width="20" height="20">
                        <span class="cctheme-text pag-hide-mobile">Realize o pagamento utilizando QR Code abaixo</span>
                        <span class="cctheme-text pag-show-mobile">Realize o pagamento utilizando código abaixo</span>
                    </div>
                    <div class="content">
                        <div class="cctheme-payment-summary">
                            <div class="<?php echo $showQrCodeMobile ? 'pag-hide-mobile' : 'pag-show-mobile'; ?>" style="margin-bottom: 5px; width: 100%"><input type="text" value="<?php echo $data['pix']['pix_string']; ?>" readonly="readonly" /></div>
                            <small class="cctheme-small summary-text  <?php echo $qrCodeClass ?>">Escaneie o QR Code abaixo utilizando a câmera do celular</small>
                            <div class="img-wrapper <?php echo $qrCodeClass ?>">
                                <div class="img">
                                    <img src="<?php echo $data['pix']['pix_qrcode']; ?>" alt="Escaneie esse QR Code para realizar o pagamento" class="cctheme-image" width="150" height="150">
                                </div>
                            </div>
                            <div class="actions-toolbar">
                                <button type="button" title="Copiar código Pix" aria-label="Copiar código Pix" class="action copy primary pix" data-clipboard-text="<?php echo $data['pix']['pix_string']; ?>">
                            <span class="cctheme-icon">
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M12.182 12.1818H16.0002V2H5.81836V5.81818" stroke="white" stroke-width="1.27273" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M12.1818 5.81824H2V16.0001H12.1818V5.81824Z" stroke="white" stroke-width="1.27273" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>
                            </span>
                                    <span class="cctheme-text">Copiar código Pix</span>
                                </button>
                            </div>
                        </div>
                        <div class="cctheme-payment-content">
                            <div class="title">
                                <div class="label">
                                    <span class="cctheme-text">Valor da sua compra:</span>
                                </div>
                                <div class="grand-total">
                                    <span class="price"><?php echo Mage::helper('core')->currency($order->getGrandTotal(), true, false); ?></span>
                                </div>
                            </div>
                            <div class="cctheme-payment-steps">
                                <div class="step">
                                    <p class="cctheme-text"><strong class="cctheme-strong">1. </strong>Abra o aplicativo do seu banco ou institução financeira e entre em Pix.</p>
                                </div>
                                <div class="step">
                                    <p class="cctheme-text"><strong class="cctheme-strong">2. </strong>Escolha a opção pagar com QR Code e escaneie o código ao lado.</p>
                                </div>
                                <div class="step">
                                    <p class="cctheme-text"><strong class="cctheme-strong">3. </strong>Caso não consiga escanerar o código, clique no botão "Copiar código PIX" e insira as informações no aplicativo do seu Banco.</p>
                                </div>

                                <div class="step">
                                    <p class="cctheme-text"><a href="<?php echo $data['pix']['pix_url']; ?>" target="_blank">Link de Pagamento</a></p>
                                </div>

                            </div>

                            <div class="cctheme-payment-brand">
                                <div>
                                    <small class="cctheme-small">pagamento processado por:</small>
                                </div>
                                <div>
                                    <a href="https://pagcommerce.com.br" target="_blank" title="Ir para o site da Pagcommerce" aria-label="Ir para o site da Pagcommerce">
                                        <img class="cctheme-image"  src="<?php echo $this->getSkinUrl('pagcommerce_payment/img/pagcommerce-pagamentos-online.webp') ?>"  alt="Pagcommerce - Pix para Ecommerce" width="96" height="21"/>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>

            <div class="cctheme-payment-block -success pix-pago" id="pix" style="display: none;">
                <div class="success-container">
                    <div style="display: flex;">
                        <svg width="140" height="140" viewBox="0 0 140 140" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <mask id="mask0_4848_3194" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="9" y="6" width="122" height="128">
                            <path d="M69.999 11.9049L85.1826 22.9812L103.979 22.9465L109.752 40.8327L124.978 51.8511L119.137 69.7142L124.978 87.5772L109.752 98.5957L103.979 116.482L85.1826 116.447L69.999 127.523L54.8154 116.447L36.0187 116.482L30.2465 98.5957L15.0195 87.5772L20.8612 69.7142L15.0195 51.8511L30.2465 40.8327L36.0187 22.9465L54.8154 22.9812L69.999 11.9049Z" fill="white" stroke="white" stroke-width="11.5618" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M49.7656 69.7142L64.2179 84.1665L93.1226 55.2618" stroke="black" stroke-width="11.5618" stroke-linecap="round" stroke-linejoin="round"/>
                            </mask>
                            <g mask="url(#mask0_4848_3194)">
                            <path d="M0.628906 0.343018H139.371V139.085H0.628906V0.343018Z" fill="#5ECF38"/>
                            </g>
                        </svg>
                    </div>
                    <div>
                        <h3 class="cctheme-text">Pagamento confirmado!</h3>
                    </div>
                    <div>
                        <p class="cctheme-text">Recebemos o seu pagamento e já estamos separando o seu pedido.</p>
                    </div>
                </div>
                <div class="cctheme-payment-brand">
                    <div>
                        <small class="cctheme-small">Processado por:</small>
                    </div>
                    <div>
                        <a href="https://pagcommerce.com.br" target="_blank" title="Ir para o site da Pagcommerce" aria-label="Ir para o site da Pagcommerce">
                            <img class="cctheme-image"  src="<?php echo $this->getSkinUrl('pagcommerce_payment/img/pagcommerce-pagamentos-online.webp') ?>"  alt="Pagcommerce - Pix para Ecommerce" width="96" height="21"/>
                        </a>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                var pixPaid = false;
                setInterval(function () {
                    if(!pixPaid){
                        var urlPix = '<?php echo $this->getUrl('pagcommerce/standard/checkorderpayment', array('order' => $order->getIncrementId())); ?>';
                        jQuery.get(urlPix, function(data){
                            if(data.status == true && data.paid == true){
                                pixPaid = true;
                                jQuery('.pix-pendente').hide();
                                jQuery('.pix-pago').show();
                            }
                        }, 'json');
                    }
                }, 3000);
            </script>
        <?php endif; ?>
    <?php endif; ?>

    <script src="<?php echo $this->getSkinUrl('pagcommerce_payment/vendor/clipboard.min.js') ?>"></script>
    <script>
         const clipboard = new ClipboardJS('.action.copy.pix');

        clipboard.on('success', function (e) {
            const currentLabel = e.trigger.innerHTML;

            e.trigger.innerHTML = '<span class="cctheme-icon"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.6875 4L6.6875 14L1.6875 9" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg> </span><span class="cctheme-text">Código copiado!</span>';

            setTimeout(() => {
                e.trigger.innerHTML = currentLabel;
            }, 1000);
        });

        const clipboard2 = new ClipboardJS('.action.copy.boleto');

        clipboard2.on('success', function (e) {
            const currentLabel = e.trigger.innerHTML;

            e.trigger.innerHTML = '<span class="cctheme-icon"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.6875 4L6.6875 14L1.6875 9" stroke="#4A4948" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg> </span><span class="cctheme-text">Código copiado!</span>';

            setTimeout(() => {
                e.trigger.innerHTML = currentLabel;
            }, 1000);
        });
    </script>
</div>
<?php endif; ?>

<style>
    .pag-show-mobile{display: none;}
    @media (max-width: 768px) {
        .pag-hide-mobile {
            display: none !important;
        }
        .pag-show-mobile {
            display: block !important;
        }
    }
</style>