<?php
/**
 * Created by PhpStorm.
 * User: eric
 * Date: 05/10/17
 * Time: 14:37
 */
class Pagcommerce_Payment_Block_Checkout_Success extends Mage_Checkout_Block_Onepage_Success {

    public function __construct(array $args = array())
    {
        parent::__construct($args);
        $this->setTemplate('pagcommerce_payment/checkout/success.phtml');
    }

    public function getOrder()
    {
        $final = "";
        $orderId       = Mage::getSingleton('checkout/session')->getLastRealOrderId();
        return Mage::getModel('sales/order')->loadByIncrementId($orderId);
    }

    public function getChildTemplate()
    {
        $order = $this->getOrder();
        if ($order) {
            $info = $order->getPayment()->getMethodInstance()->getCode();
            if ($info == "pagcommerce_payment_boleto") {
                return $this->getChildHtml('codecia.shopfacilboletobradesco.checkout.method.boleto');
            }

        }
    }

    protected function _toHtml()
    {
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}