<?php
/** @var Pagcommerce_Payment_Block_Customerarea_Cc $this */

$creditCards = $this->getCreditCardSaved();

/** @var Pagcommerce_Payment_Model_Source_CreditCard_Brand $sourceBrands */
$sourceBrands = Mage::getModel('Pagcommerce_Payment_Model_Source_CreditCard_Brand');
$brands = $sourceBrands->toArray();

?>
<div class="my-account">
    <div class="dashboard">
        <div class="page-title">
            <h1>Meus Cartões de Crédito</h1>
        </div>
        <div class="box-account box-recent">
           <?php if(!$creditCards): ?>
                <div>Nenhum cartão de crédito cadastrado</div>
           <?php else: ?>
                <div class="pag_credit_cards">
                    <?php foreach($creditCards as $creditCard): ?>
                        <div class="pg_credit_card pg_credit_card_<?php echo $creditCard['id'];  ?>">
                            <img class="brand" src="<?php echo $this->getSkinUrl('pagcommerce_payment/img/checkout/brands/'.$creditCard['card_brand'].'.svg'); ?>"/>
                            <div class="title"><?php echo $brands[$creditCard['card_brand']]; ?> de final <?php echo $creditCard['first4_digits']; ?> </div>
                            <div class="expiration">Expira em: <?php echo $creditCard['expiration_month']; ?>/<?php echo $creditCard['expiration_year']; ?></div>
                            <a href="#" class="remove-pag-card" data-id="<?php echo $creditCard['id']; ?>" data-label="<?php echo $brands[$creditCard['card_brand']]; ?> de final <?php echo $creditCard['first4_digits']; ?>">Remover</a>
                        </div>
                    <?php endforeach; ?>
                </div>
           <?php endif; ?>
        </div>
    </div>
</div>

<script>
   jQuery(document).ready(function(){
       var modal = jQuery('#confirmation-modal');
            
        jQuery('.remove-pag-card').click(function() {
            var cardId = jQuery(this).attr('data-id');
            jQuery('.confirm-button').attr('data-id', cardId);

            jQuery('.card-label').html(jQuery(this).attr('data-label'));
            modal.addClass('active');
            return false;
        });

       jQuery('.confirm-button').click(function() {
           var cardId = jQuery(this).attr('data-id');

           // AJAX PARA REMOVER CARTÃO
           jQuery.get('/pagcommerce/ajax/removecc/id/'+cardId, function(data){

           }, 'json').done(function(data) {
               if(data.status){
                   jQuery('.pg_credit_card_' + cardId).fadeOut(400);
                   jQuery('#confirmation-modal').removeClass('active');
               }else{
                   alert(data.message);
               }
           });
           return false;
       });

       jQuery('.cancel-button').click(function() {
           modal.removeClass('active');
       });

       jQuery('.modal-close').click(function() {
           modal.removeClass('active');
       });

       jQuery('.modal').click(function(e) {
           if (e.target === this) {
               modal.removeClass('active');
           }
       });


   });
</script>

<aside id="confirmation-modal" class="modal">
    <div class="modal-inner">
        <div class="modal-header">
            <h3 class="modal-title">Você tem certeza que deseja remover esse cartão de crédito?</h3>
            <button type="button" class="modal-close">
                <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M17.9488 2.46967C18.2417 2.76256 18.2417 3.23744 17.9488 3.53033L3.94879 17.5303C3.65589 17.8232 3.18102 17.8232 2.88813 17.5303C2.59523 17.2374 2.59523 16.7626 2.88813 16.4697L16.8881 2.46967C17.181 2.17678 17.6559 2.17678 17.9488 2.46967Z" fill="black"/>
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M2.88813 2.46967C3.18102 2.17678 3.65589 2.17678 3.94879 2.46967L17.9488 16.4697C18.2417 16.7626 18.2417 17.2374 17.9488 17.5303C17.6559 17.8232 17.181 17.8232 16.8881 17.5303L2.88813 3.53033C2.59523 3.23744 2.59523 2.76256 2.88813 2.46967Z" fill="black"/>
                </svg>
            </button>
        </div>
        <div class="modal-body">
            <p class="card-label"><img src="http://pagcommerce-magento1.intranet/skin/frontend/base/default/pagcommerce_payment/img/checkout/brands/mastercard.svg"/> Mastercard final 1234</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="cancel-button button2">Cancelar</button>
            <button type="button" class="confirm-button button" data-id="">Confirmar</button>
        </div>
    </div>
</aside>
